use super::*;

#[derive(Debug, Default)]
pub struct DaliWorkerCounters {
    pub commands_handled: AtomicU32,
    pub invalid_command: AtomicU32,
    pub execution_failed: AtomicU32,
    pub confirmation_publish_failed: AtomicU32,
    pub event_publish_failed: AtomicU32,
    pub evidence_publish_failed: AtomicU32,
    pub event_publish_retried: AtomicU32,
    pub event_publish_backoff_ms: AtomicU32,
    pub semantic_set_target_state_handled: AtomicU32,
    pub target_state_superseded: AtomicU32,
    pub semantic_program_group_membership_handled: AtomicU32,
    pub semantic_program_scene_handled: AtomicU32,
    pub semantic_recall_scene_handled: AtomicU32,
    pub semantic_recall_last_active_level_handled: AtomicU32,
    pub semantic_write_attributes_handled: AtomicU32,
    pub semantic_discover_devices_handled: AtomicU32,
    pub semantic_read_attributes_handled: AtomicU32,
    pub semantic_read_memory_bank_handled: AtomicU32,
    pub read_attributes_contended_aborts: AtomicU32,
    pub read_attributes_transport_aborts: AtomicU32,
    pub read_attributes_preempted: AtomicU32,
    pub write_attributes_preempted: AtomicU32,
    pub read_attributes_device_absent: AtomicU32,
    pub read_attributes_sequence_incomplete: AtomicU32,
    pub discovery_progress_events_published: AtomicU32,
    pub discovery_failed_events_published: AtomicU32,
    pub discovery_device_type_degraded: AtomicU32,
    pub bus_health_probe_failed: AtomicU32,
    pub arbitration_probe_failed: AtomicU32,
    pub handover_stand_down_failed: AtomicU32,
    pub memory_bank_chunk_events_published: AtomicU32,
    pub memory_bank_short_reads: AtomicU32,
    pub tx_suppressed_passive: AtomicU32,
    pub input_scans_completed: AtomicU32,
    pub input_devices_addressed: AtomicU32,
    pub input_config_rejected: AtomicU32,
    pub input_addresses_contended: AtomicU32,
    pub input_presence_reprobed: AtomicU32,
    pub ignored_commands: AtomicU32,
}
