[alias]
bdd = "test --target aarch64-apple-darwin -p dali2rust-bdd --test bdd"
fw = "build -p dali2rust-firmware --target riscv32imafc-esp-espidf"
flash = "run -p dali2rust-firmware --target riscv32imafc-esp-espidf"

[target.riscv32imafc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --bootloader target/riscv32imafc-esp-espidf/debug/bootloader.bin --partition-table partitions-p4.csv"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = { value = "esp32p4", force = true }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.p4.defaults", force = true }
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
ESP_IDF_SYS_ROOT_CRATE = "dali2rust-firmware"
